add check of curl failure in deployment and rm artifact creation

diff --git a/ops/ci.yaml b/ops/ci.yaml
--- a/ops/ci.yaml
+++ b/ops/ci.yaml
@@ -96,11 +96,6 @@ stages:
               --push \
               ./
             displayName: Docker build prd
-          - script: |
-              mkdir -p $(Build.ArtifactStagingDirectory)/tag
-              echo $(tag) > $(Build.ArtifactStagingDirectory)/tag/hcr.txt
-            displayName: "Save tag to file"
-
 
   - stage: trigger_deploy
     displayName: Trigger deploy
@@ -129,5 +124,9 @@ stages:
                   -H "Content-Length: $contentLength" \
                   -d "$jsonBody" \
                   https://dev.azure.com/$organization/$project/_apis/pipelines/$pipeline/runs?api-version=7.1-preview.1
+                if [ $? -ne 0 ]; then
+                  echo "Failed to trigger deploy for pipeline $pipeline"
+                  exit 1
+                fi
               done
             displayName: "Trigger deploy"
